#!/bin/bash

## Build wAx
xa -l toc/toc2k -o 2716/wax2k.bin src/wax.asm
printf "\x00\xa0" | cat - 2716/wax2k.bin > vic/wax

rm vic/wax.d64
c1541 -format wax,8 d64 vic/wax.d64 -write vic/wax

## Build wAx 4k
xa -l toc/toc4k -o 2732/wax4k.bin src/wax4k.asm
printf "\x00\x60" | cat - 2732/wax4k.bin > vic/wax4k
c1541 vic/wax.d64 -write vic/wax4k
head -c 2048 2732/wax4k.bin > 2716/wax4k-L.bin
tail -c 2038 2732/wax4k.bin > 2716/wax4k-H.bin

## Build 6502 Extended Instuction Table
xa -o src/6502x.obj src/6502x.asm
printf "\xfe\xa7" | cat - src/6502x.obj > vic/6502x
c1541 vic/wax.d64 -write vic/6502x

## Build BASIC test suite
##   Starting point
petcat -w2 -o vic/test -- tests/test.bas
c1541 vic/wax.d64 -write vic/test

##   Assemble all instructions, all addressing modes
petcat -w2 -o vic/6502test.prg -- tests/6502test.bas
c1541 vic/wax.d64 -write vic/6502test.prg

##   Verify assembly of all instructions, all addressing modes
petcat -w2 -o vic/verify.prg -- tests/verify.bas
c1541 vic/wax.d64 -write vic/verify.prg

##   Test hex and text editor
petcat -w2 -o vic/edittest.prg -- tests/edittest.bas
c1541 vic/wax.d64 -write vic/edittest.prg

##   Test the Somewhat Symbolic Assembler
petcat -w2 -o vic/symboltest.prg -- tests/symboltest.bas
c1541 vic/wax.d64 -write vic/symboltest.prg

##   Test immediate mode operand formats
petcat -w2 -o vic/immedtest.prg -- tests/immedtest.bas
c1541 vic/wax.d64 -write vic/immedtest.prg

## Build Block 3 2716 binary
sed 's/\* = \$a000/\* = \$6000/' src/wax.asm > src/wax-blk3.asm
xa -o vic/wax-blk3.bin src/wax-blk3.asm

